### ISSUE TITLE
Lifecounter - Bottom buttons in Timer do not work

### ISSUE THREAD

**Issue by Papooch** [nerudaj/AppJS#27] opened 2020-04-08 12:18 UTC
Therefore once 'Timer' is clicked, there is no way back as the 'Settings' and 'Back' buttons simply do nothing.

This bug is only present in the **release** version.

**Comment by nerudaj** [comment] 2020-04-16 16:36
This was caused by wrong version of minifier used during release process. Will be hopefully fixed in the next release.

**Closed as completed by nerudaj** 2020-04-16 16:36 UTC
Labels: bug
